apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commodity-api
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: commodity-api.dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: commodity-api
                port:
                  number: 8080