apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commodity-api
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    # Required for Azure Load Balancer probes
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: commodity-api
                port:
                  number: 80

    # Actual dev traffic
    - host: commodity-api.dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: commodity-api
                port:
                  number: 80
