name: Basic CI
description: Build & Test with dotnet.

on:
  push:
    branches-ignore: [ main ]
    paths-ignore:
      - 'terraform/**'
      - '.github/**'

permissions:
  contents: read
  checks: write
  actions: write  

jobs:
  build-and-test:
    name: Build and Test
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install nuget
        uses: nuget/setup-nuget@v3
        with:
          nuget-version: latest
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore
        
      - name: Run Unit Tests
        working-directory: src/tests
        run: |
          dotnet test Commodity.Api.UnitTests -c Release --no-restore