name: Continuous Integration for Feature Push
description: Build & Test with dotnet.

on:
  push:
    branches-ignore: [ main ]
    paths-ignore:
      - 'terraform/**'
      - '.github/**

permissions:
  contents: read
  checks: write
  actions: write  

jobs:
  ci:
    name: Build and Test
    if: github.event.pull_request == null
    runs-on: [ubuntu-latest]
    env:
      BaseUrl: http://localhost:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install nuget
        uses: nuget/setup-nuget@v3
        with:
          nuget-version: latest
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore
        
      - name: Run Unit Tests
        working-directory: src/tests
        run: |
          dotnet test Commodity.Api.UnitTests -c Release --no-restore

      - name: Build Docker Image
        working-directory: src/Commodity.Api
        run: |
          docker build -t ghcr.io/${{github.repository}}/commodity-api:${{github.SHA}} .

      - name: Run Docker Container
        working-directory: src       
        env:
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_SHA: ${{ github.sha }}
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      
      - name: Wait for API to be healthy
        working-directory: src
        run: |
          for i in {1..30}; do
            if docker compose ps --status=running --status=healthy | grep api; then
              echo "API is healthy"
              exit 0
            fi
            sleep 2
          done

          echo "API did not become healthy"
          docker compose ps
          exit 1

      - name: Run Integration Tests
        working-directory: src/tests
        run: dotnet test Commodity.Api.IntegrationTests -c Release

      - name: Post Compose logs (On Failure)
        if: failure()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml logs --no-color
      
      - name: Tear down Compose
        if: always()
        working-directory: src
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml down -v