name: Continous Integration | Push to branch
description: Builds and runs Unit tests with dotnet. Builds and runs Integration Tests against docker.

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci-base.yml
    with:
      run_trivy: true
      run_k6: true