name: build-test-sonar

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin Sonar analysis
        working-directory: src/CommodityArticle.Api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"georgenicholsondeveloper_devops-masters" \
            /o:"georgenicholsondeveloper" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${SONAR_TOKEN}"

      - name: Build
        working-directory: src/CommodityArticle.Api
        run: dotnet build -c Release

      - name: Test (with coverage)
        working-directory: src/CommodityArticle.Api
        run: dotnet test -c Release --collect:"XPlat Code Coverage" --logger "trx"

      - name: End Sonar analysis
        working-directory: src/CommodityArticle.Api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
